# Generated by Django 4.1 on 2022-08-28 12:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65)),
                ("description", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("book_author", models.CharField(max_length=65)),
                ("publication_year", models.IntegerField()),
                (
                    "conservation_state",
                    models.CharField(
                        choices=[
                            ("MN", "Muito Usado"),
                            ("U", "Usado"),
                            ("SN", "Semi-Novo"),
                            ("N", "Novo"),
                        ],
                        max_length=2,
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("publishing_company", models.CharField(max_length=65)),
                ("isbn", models.IntegerField()),
                ("review", models.TextField()),
                ("review_is_html", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "phoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=70, unique=True)),
                ("cover", models.ImageField(upload_to="books/covers/%Y/%m/%d/")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.category",
                    ),
                ),
            ],
        ),
    ]
