# Generated by Django 4.1 on 2022-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, default="", upload_to="books/covers/%Y/%m/%d/"
            ),
        ),
    ]
