# Generated by Django 4.1 on 2022-09-17 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="city",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="phoneNumber",
            field=models.CharField(max_length=15),
        ),
    ]
