# Generated by Django 4.1 on 2022-10-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_city_alter_book_phonenumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="title",
            new_name="titulo",
        ),
    ]
