# Generated by Django 4.1 on 2022-10-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_rename_title_book_titulo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="description",
            new_name="DESCRICAO",
        ),
    ]
