# Generated by Django 4.1 on 2022-10-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_rename_description_book_descricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="book_author",
            new_name="AUTOR_DO_LIVRO",
        ),
    ]
