# Generated by Django 4.1 on 2022-10-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_rename_category_categoria_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CATEGORIA",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="CATEGORIA",
            new_name="category",
        ),
    ]
