name: Django CI

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday
  DEBUG: true
  DEVELOPMENT_MODE: true

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: 'Development Mode'
        run:
          echo "1 - Development mode is $DEVELOPMENT_MODE"
          export DEVELOPMENT_MODE=True
          echo "2 - Development mode is $DEVELOPMENT_MODE"      
      - name: 'Debug'
        run: export $DEBUG

  lint:
    strategy:
        fail-fast: true
        matrix:
          python-version: ['3.9']
          os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: ${{matrix.python-version}}
        - name: Install Project 
          run:
              pip install -r requirements.txt
        - name: Check for importing style
          run: isort . 
        - name: Look for auto format errors
          run: black .

  tests:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project 
        run: python -m pip install --upgrade pip
            pip install -r requirements.txt            
      - name: tests
        run: python manage.py test -v --junitxml=test-result.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.38
